/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import model.KeyValue;
import com.sun.istack.internal.logging.Logger;
import db.Koneksi;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Asdos;
import model.Dosen;
import sun.util.calendar.BaseCalendar;
import sun.util.logging.PlatformLogger;



public class AsdosTambahFrame extends javax.swing.JFrame {
    BufferedImage bImage;
    int status;
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String qrydosen = "SELECT * FROM dosen ORDER BY nama_dosen";
    
    private final int SEDANG_TAMBAH =101;
    private final int SEDANG_UBAH =102;
    private final int IMG_WIDTH =183;
    private final int IMG_HEIGHT =224;
    
    public void rbJenisKelaminSetSelected(String jenisKelamin){
        if(jenisKelamin.equals("Laki-laki"))
            rbLaki.setSelected(true);
        else
            rbPerempuan.setSelected(true);
    }
    public String rbJenisKelaminGetSelected(){
        if(rbLaki.isSelected())
            return "Laki-laki";
        else if (rbPerempuan.isSelected())
            return "Perempuan";
        else
            return"";
    }
    public Vector getCbData (String qry,String key, String value){
      Vector v = new Vector();
      try {
          Koneksi koneksi = new Koneksi();
          Connection con = koneksi.getConnection();
          st = con.createStatement();
          rs = st.executeQuery(qry);
          while(rs.next()){
              v.addElement(new KeyValue(rs.getInt(key),
                                        rs.getString(value)));    
          }
      } catch (SQLException ex){
          System.err.println("Error getData() :"+ex);
      }
      return v;
    }
    public void cbSetModel(String qry, String key, String value, JComboBox<String> jcb){
        Vector v = getCbData(qry, key, value);
        DefaultComboBoxModel model;
        model = new DefaultComboBoxModel(v);
        jcb.setModel(model);
    }
    
    public AsdosTambahFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        eId.setText(makeId());
        eId.setEnabled(false);
        eNama.requestFocus();
        cbSetModel(qrydosen, "nip", "nama_dosen", cbDosen);
        status=SEDANG_TAMBAH;
        setTitle("Tambah Data Anggota Asisten Dosen");
    }
    public AsdosTambahFrame(Asdos asdos) {
        initComponents();
        setLocationRelativeTo(null);
        setSize(700,700);
        setTitle("Ubah Data Arsip Asdos");
        eId.setText(asdos.getId());
        eId.setEnabled(false);
        eNama.requestFocus();
        eNama.setText(asdos.getNama());
        rbJenisKelaminSetSelected(asdos.getJenisKelamin());
        jXDatePicker1.setDate(getFormattedDate(asdos.getTanggalLahir()));
        cbTupoksi.setSelectedItem(asdos.getTupoksi());
        cbSetModel(qrydosen, "nip", "nama_dosen", cbDosen);
        cbSetSelected(asdos.getDosen(). getNamadosen(),cbDosen);
        bImage = getBufferedImage(asdos.getFotoAsdos());
        lbGambar.setIcon(new ImageIcon(bImage));
        status = SEDANG_UBAH;
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        eId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        eNohp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbDosen = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbTupoksi = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbGambar = new javax.swing.JLabel();
        bPilih = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id");

        jLabel2.setText("Nama Lengkap");

        buttonGroup1.add(rbLaki);
        rbLaki.setText("Laki - Laki");

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Tanggal Lahir");

        jLabel5.setText("No Hp");

        jLabel6.setText("Tugas Pokok Asdos");

        cbDosen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-item1-", " ", " ", " " }));

        jLabel7.setText("Dosen");

        cbTupoksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Pekerjaan--", "Penelitian", "Mengajar", "Input Data", "Pengolah Data" }));

        jLabel8.setText("Foto Data Diri");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        bPilih.setText("Pilih Gambar");
        bPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPilihActionPerformed(evt);
            }
        });

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(bSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBatal))
                    .addComponent(eNama)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eNohp)
                    .addComponent(cbTupoksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDosen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbLaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPerempuan))
                            .addComponent(eId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbLaki)
                        .addComponent(rbPerempuan)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbTupoksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPilih)
                    .addComponent(bSimpan)
                    .addComponent(bBatal))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String makeId(){
        String id,idDate,idSem = null;
        Date now = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyyMM");
        idDate = df.format(now);
        id = idDate+"001";
        try{
            Koneksi koneksi = new Koneksi();
            Connection connetion = koneksi.getConnection();
            
            String query = "SELECT id FROM asdos where id LIKE ?"
                    + "ORDER BY id DESC";
//            
            ps = connetion.prepareStatement(query);
            ps.setString(1, idDate+"%");
            rs = ps.executeQuery();
            
            while(rs.next()){
                idSem = rs.getString(1);
                break;
            }
        } catch (SQLException ex){
            System.err.println("Error makeId() : "+ex);
        }
        if(idSem!=null){
            int angka = Integer.parseInt(idSem.substring(6, 9));
            angka++;
            id=idDate+String.format("%03d", angka);
            }
            return id;
        }
    public void cbSetSelected(String data, JComboBox<String> cb){
        KeyValue item = new KeyValue();
       for (int i = 0; i < cb.getItemCount(); i++)
       {
           cb.setSelectedIndex(i);
           item.setValue(((KeyValue)cb.getSelectedItem()).getValue());
           if (item.getValue().equalsIgnoreCase(data))
           {
               cb.setSelectedIndex(i);
               break;
           }
       }
    }

    public Date getFormattedDate (String tanggal){
         try {
             Date tanggalLahir = dateFormat.parse(tanggal);
             return tanggalLahir;
         } catch (ParseException ex) {
             System.err.println("Error Tanggal :"+ex);
             return new Date();
         }
     }
    public BufferedImage getBufferedImage(Blob imageBlob) {
         InputStream binaryStream = null;
         BufferedImage b = null;
         try { 
             binaryStream = imageBlob.getBinaryStream();
             b = ImageIO.read(binaryStream);
         } catch (SQLException | IOException ex) {
             System.err.println("Error getBufferedImage : "+ex);
         }
         return b;      
    }
    public Blob getBlobImage(BufferedImage bi) {
         ByteArrayOutputStream baos = new ByteArrayOutputStream();
         Blob blFile = null;
         try {
             ImageIO.write(bi, "png", baos);
             blFile = new javax.sql.rowset.serial.SerialBlob(baos.toByteArray());
         } catch (SQLException | IOException ex) {
             //Logger.getLogger(AnggotaTambahFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
         return blFile;
     }
     private BufferedImage resizeImage(BufferedImage originalImage, int type){
         BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
         Graphics2D g = resizedImage.createGraphics();
         g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
         g.dispose();
         return resizedImage;
         }  
    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
       AsdosTambahFrame a = new AsdosTambahFrame();
        a.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bBatalActionPerformed

    private void bPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPilihActionPerformed
         FileNameExtensionFilter filter  = new FileNameExtensionFilter("Image Files", 
                                                        "jpg", "png", "gif", "jpeg");
        fChooser.setFileFilter(filter);
        BufferedImage img = null;
        try {
            int result = fChooser.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION){
                File file = fChooser.getSelectedFile();
                img = ImageIO.read(file);
                int type = img.getType() == 0? BufferedImage.TYPE_INT_ARGB : img.getType();
                bImage = resizeImage(img, type);
                lbGambar.setIcon(new ImageIcon(bImage));
            }
        } catch (IOException e) {
            System.err.println("Error bPilih : "+e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bPilihActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        Asdos asdos = new Asdos();
        asdos.setId(eId.getText());
        asdos.setNama(eNama.getText());
        asdos.setJenisKelamin(rbJenisKelaminGetSelected());
        asdos.setTanggalLahir(dateFormat.format(jXDatePicker1.getDate()));
        asdos.setNoHp(eNohp.getText());
        asdos.setTupoksi(cbTupoksi.getSelectedItem().toString());
        asdos.setFotoAsdos(getBlobImage(bImage));
        
        Dosen dosen = new  Dosen();
        dosen.setNip(((KeyValue)cbDosen.getSelectedItem()).getKey());
        asdos.setDosen(dosen);
        if(asdos.getNama().equalsIgnoreCase("") ||
           asdos.getJenisKelamin().equalsIgnoreCase("") ||
           asdos.getTanggalLahir().equalsIgnoreCase("") ||
           asdos.getNoHp().equalsIgnoreCase("") ||
           asdos.getTupoksi().equalsIgnoreCase("- Pilih Pekerjaan -")||
           asdos.getFotoAsdos()==null){
           JOptionPane.showMessageDialog(null, "Lengkapi data");
        }else{
            
            Koneksi koneksi = new Koneksi();
            Connection con = koneksi.getConnection();
            PreparedStatement ps;
            try {
             if(status==SEDANG_TAMBAH){
                    String qry = "insert into asdos values (?,?,?,?,?,?,?,?)";
                    
                    ps = con.prepareStatement(qry);
                    ps.setString(1, asdos.getId());
                    ps.setString(2, asdos.getNama());
                    ps.setString(3, asdos.getJenisKelamin());
                    ps.setString(4, asdos.getTanggalLahir());
                    ps.setString(5, asdos.getNoHp());
                    ps.setString(6, asdos.getTupoksi());
                    ps.setInt(7, asdos.getDosen().getNip());
                    ps.setBlob(8, asdos.getFotoAsdos());
//                    ps.executeUpdate();
            }else{
               String qry = "update asdos set nama = ?,"   
                       + "jenis_kelamin = ?, tgl_lahir = ?,"
                       + "no_hp =?, tupoksi = ?, nip_dosen =?,"
                       + "foto_asdos = ? WHERE id =?";
                ps = con.prepareStatement(qry);
                ps.setString(1, asdos.getNama());
                ps.setString(2, asdos.getJenisKelamin());
                ps.setString(3, asdos.getTanggalLahir());
                ps.setString(4, asdos.getNoHp());
                ps.setString(5, asdos.getTupoksi());
                ps.setInt(6, asdos.getDosen().getNip());
                ps.setBlob(7, asdos.getFotoAsdos());
                ps.setString(8, asdos.getId());
//                ps.executeUpdate();
            }
             ps.executeUpdate();
          }catch (SQLException ex){
              System.err.println("Error Insert/Update : "+ex);
        }
         AsdosTampilFrame a = new AsdosTampilFrame();
         a.setVisible(true);
        dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bSimpanActionPerformed

   
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsdosTambahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsdosTambahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsdosTambahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsdosTambahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsdosTambahFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bPilih;
    private javax.swing.JButton bSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDosen;
    private javax.swing.JComboBox<String> cbTupoksi;
    private javax.swing.JTextField eId;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField eNohp;
    private javax.swing.JFileChooser fChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lbGambar;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    // End of variables declaration//GEN-END:variables
}
